### ISSUE TITLE
Code coverage warning: "No source for code: '/my/local/folder/_run_response_middleware'. (couldnt-parse)"

### ISSUE THREAD

**Issue by NonStatic2014** [sanic-org/sanic#2345] opened 2021-12-29 20:10 UTC
**Describe the bug**
After upgrade sanic from 21.6 to 21.9, coverage, we noticed when run `coverage xml`, there is an error like below:

```
No source for code: '/my/local/folder/_run_request_middleware'.
```

with `coverage xml -i` there are more warnings:

```
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/_run_request_middleware': No source for code: '/my/local/folder/_run_request_middleware'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/_run_response_middleware': No source for code: '/my/local/folder/_run_response_middleware'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/connection_task': No source for code: '/my/local/folder/connection_task'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/handle_exception': No source for code: '/my/local/folder/handle_exception'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/handle_request': No source for code: '/my/local/folder/handle_request'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/http1_request_header': No source for code: '/my/local/folder/http1_request_header'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/http1_response_header': No source for code: '/my/local/folder/http1_response_header'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/read': No source for code: '/my/local/folder/read'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/my/local/virtualenv/lib/python3.8/site-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/my/local/folder/send': No source for code: '/my/local/folder/send'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
Wrote XML report to coverage.xml
```

**Code snippet**

In blueprint.py

```
my_bp = Blueprint("my_blueprint")
```

Create app in a different file:

```
my_app = Sanic(name, load_env=False, log_config=LOG_SETTINGS)
my_app.blueprint(my_bp)
my_app.register_middleware( ..... )
```

**Expected behavior**
No warning or error while generating code coverage report, like using sanic 21.6.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 21.9 and 21.12, not repro on 21.6
 - Python: 3.8

**Additional context**
```bash
$ pip freeze | grep "sanic\|coverage\|pytest"
coverage==6.2
pytest==6.2.5
pytest-asyncio==0.15.1
sanic==21.9.3
sanic-routing==0.7.2
sanic-testing==0.8.2
```

**Comment by ahopkins** [comment] 2021-12-29 20:14
Why are you running coverage for Sanic?

You will not get coverage for these functions because they are rewritten at startup time based upon your application's code.

**Comment by NonStatic2014** [comment] 2021-12-29 20:21
I'm trying to run coverage on my server code but hit error/warning on sanic code. this is the place actually confused me.

**Comment by NonStatic2014** [comment] 2021-12-29 20:22
`blueprint.py` and other python code of my server is in the folder `/my/local/folder/`. I don't expect any coverage number from sanic.

**Comment by ahopkins** [comment] 2021-12-29 21:53
However you are running coverage, it is including the portions of Sanic that are imported into your application. What version of `coverage` are you using? [See this article](https://nedbatchelder.com/blog/202104/coveragepy_and_thirdparty_code.html).


> And can you explain a little more about this?

Sure! This is an important feature of Sanic going forward. I am myself working out this whole coverage issue because it is a PITA. We handle it currently by simply ignoring those methods. Not ideal.

What is happening is that when you first load Sanic, it does some self inspection of the types of handlers that you have setup. Currently it is looking for a few specific items: (1) what signals are implemented by the application; and (2) what `content_type` is each route handler _likely_ to produce. The first item is used to trim out unneeded code from executing, thus making Sanic more efficient. The second is used to determine how to handle error formatting in an appropriate manner.

In the coming year, there likely will be some more of these introspection style optimizations.

**Comment by ahopkins** [comment] 2021-12-29 21:54
I am closing this now as the issue is not really related to Sanic. Feel free to continue the conversation.

**Closed by ahopkins** 2021-12-29 21:54 UTC

**Comment by rbm-radius** [comment] 2023-02-24 22:38
@ahopkins respectfully I'd like to reopen this--it _is_ a Sanic issue because of the generated code, which causes confusion with other tools looking for persistent modules. No other package I've used out of ~250 in my current app does this.

**Comment by ahopkins** [comment] 2023-02-26 09:07
Feel free to create a new issue and reference this. I would ask @rbm-radius if you can provide a use case and a simple repeatable example of how/where this is causing problems.
