### ISSUE TITLE
Error handlers are synchronous

### ISSUE THREAD

**Issue by lovasoa** [sanic-org/sanic#1785] opened 2020-02-17 17:57 UTC
**Describe the bug**
The [documentation](https://sanic.readthedocs.io/en/latest/sanic/exceptions.html) says that error handlers can be asynchronous.
However, asynchronous error handlers do not seem to be supported everywhere.

**Code snippet**
```py
@app.exception(Exception)
async def handle_base_exception(_request: Request, exception: Exception):
    return response.json("too bad")
```

**Expected behavior**
Then, for example when I exceed the `REQUEST_MAX_SIZE` limit, I would expect to receive `"too bad"` as a response.

Unfortunately, sanic contains code like https://github.com/huge-success/sanic/blob/91f6abaa81248189fbcbdf685e8bdcbb7846609f/sanic/server.py#L577-L579

which expects the error handler to be synchronous.

**Actual behavior**

Here are the (verbose) logs of the actual results:

```
2020-02-17 19:03:15,514:INFO:
[2020-02-17 19:03:24 +0100] [37783] [ERROR] Transport closed @ ('127.0.0.1', 58698) and exception experienced during error handling
[2020-02-17 19:03:24 +0100] - (sanic.access)[INFO][UNKNOWN]: nil  0 -1
2020-02-17 19:03:24,145:ERROR:Transport closed @ ('127.0.0.1', 58698) and exception experienced during error handling
2020-02-17 19:03:24,145:INFO:
.../venv/lib/python3.7/site-packages/sanic/server.py:297: RuntimeWarning: coroutine 'handle_base_exception' was never awaited
  self.write_error(PayloadTooLarge("Payload Too Large"))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by Tronic** [comment] 2020-02-21 07:19
This one seems to be hard to fix because of how asyncio protocols work. The `server.write_error` function is non-async and thus cannot await on the response, and the function is also called from non-async callbacks that cannot be made async because of how `asyncio` is built.

I suppose this could be worked around by using `asyncio.create_task(...)` but doing so might introduce some unexpected effects and since the protocol code is in any case quite convoluted, I am not quite confident enough to just go changing it.

Anyone willing to weigh in, or should I just modify the code and see if tests break?

**Comment by Tronic** [comment] 2020-03-01 13:39
I've confirmed that this is now fixed in the streaming branch.

**Comment by lovasoa** [comment] 2020-05-30 16:57
This should probably not be closed  until the fix is merged

**Comment by wei-hai** [comment] 2020-07-23 23:48
+1

**Comment by lovasoa** [comment] 2020-10-22 07:01
No, this issue is not stale, it still hasn't been fixed

**Closed** 2021-01-10 22:45 UTC
Labels: necessary
