### ISSUE TITLE
With or without trailing slash will be matched to different endpoints

### ISSUE THREAD

**Issue by ZSSVE** [sanic-org/sanic#2411] opened 2022-03-15 21:49 UTC
**Describe the bug**

Hi, during our upgrade of Sanic from 19.9.0 to a higher one at 21.9.3, we ran into a seemly behavior change for path routing.

**A clear and concise description of what the bug is, make sure to paste any exceptions and tracebacks.**

With two GET endpoints

1. /test/
2. /test/< name>

In Sanic 19.9.0,

- `curl 'http://127.0.0.1:8000/test/'` will be routed to endpoint 1

In Sanic 21.9.3,

- `curl 'http://127.0.0.1:8000/test/'` will be routed to endpoint 2 with empty string as parameter

In both Sanic 19.9.0 and 21.9.3, `curl 'http://127.0.0.1:8000/test'`  resolves to endpoint 1, expectedly.

**Code snippet**
Relevant source code, make sure to remove what is not necessary.

```
from sanic import Sanic
from sanic.response import text

app = Sanic("MyHelloWorldApp")

@app.get("/test/")
async def hello_test(request):
    return text("Hey test")

@app.get("/test/<name>")
async def hello_test_name(request, name):
    return text("Hello, " + name)


if __name__ == "__main__":
    app.run("localhost", 8000)
```

**Expected behavior**

This backward incompatibility does not seem to be documented.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] big sur
 - Version [e.g. 0.8.3] 21.9.3

**Additional context**

We'll appreciate helps on a way to keep the old behavior for a smooth transition.

**Comment by Tronic** [comment] 2022-03-15 22:51
This will be mostly fixed in the next release, with the parameters no longer matching empty strings by default. I recommend always setting `Sanic("yourapp", strict_slashes=True)` to avoid such issues with all Sanic versions.

**Comment by ZSSVE** [comment] 2022-03-16 05:40
> This will be mostly fixed in the next release, with the parameters no longer matching empty strings by default. I recommend always setting `Sanic("yourapp", strict_slashes=True)` to avoid such issues with all Sanic versions.

Thank you for the reply! Since in pre-21.3 version, both `/test/` and `/test` seem to route to the endpoint without parameter (`hello_test`), we might have existing callers using both. Just adding  `strict_slashes=True` may break some of the callers. One way we are thinking about temporarily is to set `strict_slashes=True` and add a pair of routes (with and without trailing slash) for all our endpoints, but we are unsure if there are other subtle differences from the pre-21.3 behavior.

**Comment by ashleysommer** [comment] 2022-03-16 07:08
Yeah, this was a regression (or unintended change in behavior) in v21.3, caused by the introduction of the new Router, it was not corrected until recently. As @Tronic said, this will revert to the pre-21.3 behavior in the next release (v22.3), and you will not need to add `strict_slashes=True`.

**Comment by Tronic** [comment] 2022-03-16 10:36
Closing as duplicate of #2391 #2384 #2239

PR fixing the regression: https://github.com/sanic-org/sanic-routing/pull/58
An open issue with relevant discussion: https://github.com/sanic-org/sanic-guide/issues/92

**Closed by Tronic** 2022-03-16 10:36 UTC
