### ISSUE TITLE
pypy Shutting down OSError

### ISSUE THREAD

**Issue by lishichao1181** [sanic-org/sanic#2652] opened 2023-01-10 07:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[2023-01-10 15:24:25 +0000] [26100] [INFO] Stopping worker [26100]
Exception in callback BaseSelectorEventLoop._accept_connection(functools.par...ne, unix=None), <socket.socke...0.0.1', 8000)>, None, <Server socke....1', 8000)>,)>, 100, None)
handle: <Handle BaseSelectorEventLoop._accept_connection(functools.par...ne, unix=None), <socket.socke...0.0.1', 8000)>, None, <Server socke....1', 8000)>,)>, 100, None)>
Traceback (most recent call last):
  File "/usr/local/pypy3.9/lib/pypy3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/pypy3.9/lib/pypy3.9/_contextvars.py", line 44, in run
    return callable(*args, **kwargs)
  File "/usr/local/pypy3.9/lib/pypy3.9/asyncio/selector_events.py", line 159, in _accept_connection
    conn, addr = sock.accept()
  File "/usr/local/pypy3.9/lib/pypy3.9/socket.py", line 293, in accept
    fd, addr = self._accept()
OSError: [Errno 22] Invalid argument
Exception in callback BaseSelectorEventLoop._accept_connection(functools.par...ne, unix=None), <socket.socke...0.0.1', 8000)>, None, <Server socke....1', 8000)>,)>, 100, None)
handle: <Handle BaseSelectorEventLoop._accept_connection(functools.par...ne, unix=None), <socket.socke...0.0.1', 8000)>, None, <Server socke....1', 8000)>,)>, 100, None)>
Traceback (most recent call last):
  File "/usr/local/pypy3.9/lib/pypy3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/pypy3.9/lib/pypy3.9/_contextvars.py", line 44, in run
    return callable(*args, **kwargs)
  File "/usr/local/pypy3.9/lib/pypy3.9/asyncio/selector_events.py", line 159, in _accept_connection
    conn, addr = sock.accept()
  File "/usr/local/pypy3.9/lib/pypy3.9/socket.py", line 293, in accept
    fd, addr = self._accept()
OSError: [Errno 22] Invalid argument

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

CentOS Linux release 7.6.1810 (Core) 

### Sanic Version

Sanic 22.12.0; Routing 22.8.0

**Comment by SaidBySolo** [comment] 2023-01-10 08:00
Duplicate of https://github.com/sanic-org/sanic/issues/2602

**Closed** 2023-01-10 08:03 UTC
