### ISSUE TITLE
sanic.exceptions.SanicException: Sanic app name "Example" not found.

### ISSUE THREAD

**Issue by zx8** [sanic-org/sanic#2560] opened 2022-10-07 08:11 UTC
Using Sanic v22.9.0 – this used to work but recently has broken.

Here's a minimal repro of the issue:

```python
from sanic import Sanic


class Example(Sanic):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, name="Example", **kwargs)


class Application:
    def __init__(self):
        self.app = Example()

    def start(self):
        self.app.run()


if __name__ == "__main__":
    Application().start()
```

My code is structured similarly to the above. When I run it, I get:

```
Process Sanic-Server-0-0:
Traceback (most recent call last):
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'Example'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/worker/serve.py", line 51, in worker_serve
    app = app_loader.load()
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/worker/loader.py", line 60, in load
    return self.factory()
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/app.py", line 1456, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
sanic.exceptions.SanicException: Sanic app name "Example" not found.
[2022-10-07 09:07:58 +0100] [11614] [ERROR] Not all workers are ack. Shutting down.
[2022-10-07 09:07:58 +0100] [11614] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/mixins/startup.py", line 851, in serve
    manager.run()
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/worker/manager.py", line 63, in run
    self.monitor()
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/worker/manager.py", line 99, in monitor
    self.wait_for_ack()
  File "./tempenv-3dde5245c64/lib/python3.10/site-packages/sanic/worker/manager.py", line 139, in wait_for_ack
    sys.exit(1)
SystemExit: 1
```

**Comment by ahopkins** [comment] 2022-10-07 10:06
This is not a bug. Your instantiation of the app only happens in the main process. See the release notes about the recent changes to the worker. Should should instantiate app outside the if statement.

**Comment by ahopkins** [comment] 2022-12-18 12:15
I am working on some more documentation and a blog article about this. Closing.

**Closed by ahopkins** 2022-12-18 12:15 UTC
