### ISSUE TITLE
Using app.static twice reports a deprecation warning

### ISSUE THREAD

**Issue by jschewebbn** [sanic-org/sanic#2674] opened 2023-02-07 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am serving 2 different static directories, when calling app.static a second time I get a warning:
```
DeprecationWarning: [DEPRECATION v23.3] Duplicate route names detected: __main__.static. In the future, Sanic will enforce uniqueness in route naming.
```

### Code snippet

```python
app = Sanic(__name__)
app.static('/static', str(SCRIPT_DIR.joinpath('static_content').resolve()))
app.static('/static_common', str(SCRIPT_DIR.joinpath('../common_content').resolve()))
```

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

v22.12.0

**Comment by Tronic** [comment] 2023-02-07 20:09
Both routes are named `static`, which is why you get that warning. Provide a different name for at least one of them:
```python
app.static('/static', str(SCRIPT_DIR.joinpath('static_content').resolve()))
app.static('/static_common', str(SCRIPT_DIR.joinpath('../common_content').resolve()), name='static_common')
```

Closing as not a bug. For support issues, please refer to [Sanic Community Forums](https://community.sanicframework.org/c/questions-and-help/6)

**Closed by Tronic** 2023-02-07 20:09 UTC

**Comment by jschewebbn** [comment] 2023-02-07 20:13
@Tronic  how do I specify another name? "static" is a special function on app. I'm not aware of how to do this. Can you point me at documentation or an example?

**Comment by ahopkins** [comment] 2023-02-07 20:30
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/using-app-static-twice-reports-a-deprecation-warning/1146/1
