### ISSUE TITLE
Sanic app name not found

### ISSUE THREAD

**Issue by jamesstidard** [sanic-org/sanic#2570] opened 2022-10-13 12:15 UTC
**Describe the bug**

I see Sonic has been updated to a new process manager, which I think is causing me the error `sanic.exceptions.SanicException: Sanic app name "my_app" not found.`.

I read that you want to pull the `sanic.Sanic.run` function out from global space in the patch notes, which I've done, though I get the above error, different to the one mentioned in the notes.

Thanks for any pointers.

**Code snippet**
```python
from sanic import Sanic
from sanic.response import text


def hello(request):
    return text("Hello, world.")


def main():
    app = Sanic("my_app")
    app.add_route(hello, "/")
    app.run("0.0.0.0", 8000)


if __name__ == "__main__":
    main()
```

Run with:

```console
$ python main.py
```

```console
[2022-10-13 13:12:26 +0100] [27604] [INFO] 
  ┌────────────────────────────────────────────────────────────────┐
  │                         Sanic v22.9.0                          │
  │                Goin' Fast @ http://0.0.0.0:8000                │
  ├───────────────────────┬────────────────────────────────────────┤
  │                       │     mode: production, single worker    │
  │     ▄███ █████ ██     │   server: sanic, HTTP/1.1              │
  │    ██                 │   python: 3.10.4                       │
  │     ▀███████ ███▄     │ platform: macOS-12.6-x86_64-i386-64bit │
  │                 ██    │ packages: sanic-routing==22.8.0        │
  │    ████ ████████▀     │                                        │
  │                       │                                        │
  │ Build Fast. Run Fast. │                                        │
  └───────────────────────┴────────────────────────────────────────┘

[2022-10-13 13:12:26 +0100] [27604] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
Process Sanic-Server-0-0:
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/sanic/app.py", line 1450, in get_app
    return cls._app_registry[name]
KeyError: 'my_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File ".../python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./.venv/lib/python3.10/site-packages/sanic/worker/serve.py", line 51, in worker_serve
    app = app_loader.load()
  File "./.venv/lib/python3.10/site-packages/sanic/worker/loader.py", line 60, in load
    return self.factory()
  File "./.venv/lib/python3.10/site-packages/sanic/app.py", line 1456, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
sanic.exceptions.SanicException: Sanic app name "my_app" not found.
[2022-10-13 13:12:32 +0100] [27604] [ERROR] Not all workers are ack. Shutting down.
[2022-10-13 13:12:32 +0100] [27604] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/sanic/mixins/startup.py", line 851, in serve
    manager.run()
  File "./.venv/lib/python3.10/site-packages/sanic/worker/manager.py", line 63, in run
    self.monitor()
  File "./.venv/lib/python3.10/site-packages/sanic/worker/manager.py", line 99, in monitor
    self.wait_for_ack()
  File "./.venv/lib/python3.10/site-packages/sanic/worker/manager.py", line 139, in wait_for_ack
    sys.exit(1)
SystemExit: 1
[2022-10-13 13:12:32 +0100] [27604] [INFO] Server Stopped
```

**Expected behavior**

**Environment (please complete the following information):**

 - OS: `macOS 12.6`
 - Sanic Version: `22.9.0`

**Additional context**
Will run without error using `legacy=True` or `single_process=True`. Would like to update the code to run with the new method though.

**Comment by Tronic** [comment] 2022-10-13 13:23
You need to make the app a global variable, outside of the main function.

Duplicate of #2559

**Comment by ahopkins** [comment] 2022-10-13 14:32
I'll add to the docs tonight.

**Closed** 2022-10-13 14:32 UTC
Labels: bug
