### ISSUE TITLE
url_for() doesn't return a working URI for a route with the trailing slash and strict_slashes=True

### ISSUE THREAD

**Issue by hatarist** [sanic-org/sanic#1420] opened 2018-11-25 21:56 UTC
**Describe the bug**
Say we have a route with the trailing slash and `strict_slashes=True`:
`@app.route('/endpoint/', strict_slashes=True)`
this way, `url_for()` will always trim the trailing slash, returning a non-working URL.

**Code snippet**
```python
from sanic import Sanic
from sanic.response import html

app = Sanic()

# @app.route('/endpoint', strict_slashes=True)
@app.route('/endpoint/', strict_slashes=True)
async def endpoint(request):
    return html('OK')


@app.route('/')
async def index(request):
    # print(request.app.router.routes_all)
    return html('<a href="' + request.app.url_for('endpoint') + '">endpoint</a>')


if __name__ == '__main__':
    app.run(port=8000)
```

**Expected behavior**
In my example, `request.app.url_for('endpoint')` is expected to return `'/endpoint/'`.

**Environment (please complete the following information):**
 - Version 0.8.3

**Additional context**
The current implementation of `url_for()` just blindly removes the trailing slash, see [app.py, lines 617-618](https://github.com/huge-success/sanic/blob/7c182f63c8aee1d6cb31aabf6408595b195685ae/sanic/app.py#L617-L618).

**Comment by ahopkins** [comment] 2018-11-25 22:29
I confirmed the behavior. @hatarist Do you think you could take a swing at a PR?

**Comment by vltr** [comment] 2018-11-26 12:11
To be honest, I was never a fan of the `strict_slashes` option ... But I know this can lead to [large discussions](https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url), so I won't discuss that.

My only concern is that the Sanic router [doesn't actually save](https://github.com/huge-success/sanic/blob/aa0874b6d8b74f82a086098b111ffe63b2774ff9/sanic/router.py#L127-L149) on `Router.add` the value of the `strict_slashes` parameter, which can be set manually (as a parameter, exactly like @hatarist example) or, if `None`, [assume the value](https://github.com/huge-success/sanic/blob/aa0874b6d8b74f82a086098b111ffe63b2774ff9/sanic/app.py#L176-L177) of `app.strict_slashes`, that we may not know if it was overwritten by the parameter.

IMHO, to fix this, we might need to add more complexity to the router (saving the actual value of `strict_slashes` to the [`Route namedtuple`](https://github.com/huge-success/sanic/blob/aa0874b6d8b74f82a086098b111ffe63b2774ff9/sanic/router.py#L13-L15)) :grimacing:

As a matter of fact, [looking closely](https://github.com/huge-success/sanic/blob/aa0874b6d8b74f82a086098b111ffe63b2774ff9/sanic/router.py#L159-L182), I don't think the Router may even care about the `strict_slashes` option. I need to take a closer look at this, in the router level, to understand what this means ... But this just doesn't feels right :neutral_face:

**Comment by harshanarayana** [comment] 2018-11-26 16:07
@vltr  I agree with you on the amount of changes required to address this the right way. However, the current implementation contradicts with the `strict_slashes` behavior that is already enforced on other parts of the `sanic` framework.

I believe it might be a good idea to move the [Route namedtuple](https://github.com/huge-success/sanic/blob/aa0874b6d8b74f82a086098b111ffe63b2774ff9/sanic/router.py#L13-L15) into a class of it's own with `__slots__` so that we can add some helpful features into it which includes handling the `strict_slashes` etc. 

When I was looking at the router to add this comment, I noticed that the current implementation we have for `add(self, uri, methods, handler, host=None, strict_slashes=False, version=None, name=None)` is a bit confusing to understand and IMHO,  it can be simplified to make it more readable   and easy to modify as part of development if required.

**Comment by ahopkins** [comment] 2018-11-26 16:46
> I believe it might be a good idea to move the Route namedtuple into a class of it's own with __slots__ so that we can add some helpful features into it which includes handling the strict_slashes etc.

+1 I like this idea @harshanarayana 

Without sidetracking this conversation too much ... Let's open this discussion on the forums about **what** to do with the router. The December release is coming up fast, and if we want to have a chance at putting in a new router implementation (or resolving some of the existing issues) by March, let's make some decisions soon.

**Comment by harshanarayana** [comment] 2018-11-26 16:58
@ahopkins @vltr If everyone is okay with it, the quick way to fix this issue without changing too much and the core router implementation is to remove the forced removal of the trailing `/` in the `url_for` method. 
If not that, then we should be able to leverage the `app.strict_slashes`. However, this means we are enforcing the `strict_slashes` directly at the app level rather than the route level. 

The last and not so good way to fix is to leverage the `**kwargs` param provided in the `url_for`. Take an additional argument `strict_slashes` and based on this handle the return URL the right way.

**Comment by vltr** [comment] 2018-11-27 09:50
I agree with @ahopkins to take this discussion to the community forums. We can also take the discussion on #1386 regarding routing there as well - @hatarist I think you will be onboard since you gave a lot of insigts on the related issue. Just a couple of notes here:

> However, the current implementation contradicts with the `strict_slashes` behavior that is already enforced on other parts of the `sanic` framework.

Indeed, this is something that will need a lot of attention to fix "sanic-wise".

> I believe it might be a good idea to move the [Route namedtuple](https://github.com/huge-success/sanic/blob/aa0874b6d8b74f82a086098b111ffe63b2774ff9/sanic/router.py#L13-L15) into a class of it's own with `__slots__` so that we can add some helpful features into it which includes handling the `strict_slashes` etc.

That I couldn't agree more. Interacting with the `Route` itself would need some careful work because we have Blueprints and etc, but in general I really like this idea and it would help to decouple the Router logic - which I would love to see specially with a proper interface and without bouncing methods here and there - see #1317 and PR #1373 as examples of technical debts within the Router).

> ... the quick way to fix this issue without changing too much and the core router implementation is ...

I don't think we should do any quick fix presuming _this_ or _that_ because it will eventually fail :pensive:

> The last and not so good way to fix is to leverage the `**kwargs` param provided in the `url_for`.

I don't like this option either: the developer will end up setting `strict_slashes` all over the place for a design choice and, when properly fixed, this will still hang on a lot of codes as _the correct way to do it_.

**Comment by vltr** [comment] 2018-12-04 11:33
@MichaelYusko I think we need to take this matter to the forums for a better discussion, because the "correct way" of fixing this is way bellow the `url_for` method ...

**Comment by MichaelYusko** [comment] 2018-12-04 11:35
@vltr Thanks, okay will jump into the forum;)

**Comment by vltr** [comment] 2018-12-04 11:40
@MichaelYusko actually we need to create that discussion in the forum ... Oh my. Sorry, my head is over the clouds today.

**Comment by vltr** [comment] 2018-12-04 11:40
I'll start the discussion and post the link here ASAP ...

**Comment by MichaelYusko** [comment] 2018-12-04 12:02
@vltr Gotcha, no worries;) start of the week, is always hard ;-)

**Comment by vltr** [comment] 2018-12-04 12:58
@MichaelYusko yeah, sort of ... Busy day in here.

Also, @hatarist @ahopkins @harshanarayana take a look at the [community forums](https://community.sanicframework.org/t/strict-slashes-attribute-unbound-to-the-route-router/124) for that matter.

**Comment by mikeylight** [comment] 2018-12-04 13:07
@vltr Thanks, will follow up the thread on the forums.

**Comment by 5onic** [comment] 2019-05-12 11:03
@vltr which a status of the issue?

**Comment by ahopkins** [comment] 2019-05-13 09:34
@5onic No one is working on anything router related right now. Feel free to make the PR. This is also a question whether @huge-success/sanic-core-devs think this is something that we should also patch **18.12LTS**.

**Comment by 5onic** [comment] 2019-05-13 09:44
@ahopkins Cool, I'll start work on it in 3-4 days.

**Comment by Tronic** [comment] 2019-09-05 10:24
What happened to this? Trailing slashes still go missing.

**Closed** 2021-03-01 13:30 UTC
Labels: beginner, bug, help wanted
