### ISSUE TITLE
There is an obvious bug in ASGI WebsocketConnection of Sanic

### ISSUE THREAD

**Issue by piekey1994** [sanic-org/sanic#2638] opened 2022-12-21 02:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I started my sanic app with UvicornWorker. The original websocket will become WebsocketConnection. When I call
the ws.recv function will report an error if bytes data is received at this time.
`KeyError：‘text’`
[https://github.com/sanic-org/sanic/blob/main/sanic/server/websockets/connection.py](url)
`    async def recv(self, *args, **kwargs) -> Optional[str]:
        message = await self._receive()

        if message["type"] == "websocket.receive":
            return message["text"]
        elif message["type"] == "websocket.disconnect":
            pass

        return None`
There is no data of bytes type processed here.

### How do you run Sanic?

ASGI

### Operating System

ubuntu

### Sanic Version

22.3

**Comment by ahopkins** [comment] 2022-12-21 07:59
I cannot reproduce this on `main`, or even on `22.3` using uvicorn.


```py
from sanic import Request, Sanic

app = Sanic("TestApp")


@app.websocket("/feed")
async def feed(request: Request, ws):
    while True:
        data = await ws.recv()
        await ws.send(data)
```

I am closing this now as I see no bug. If you have a reproducible snippet, please send.

**Comment by piekey1994** [comment] 2022-12-21 08:19
> https://github.com/sanic-org/sanic/blob/main/sanic/server/websockets/connection.py
main.py
`from sanic import Sanic

app = Sanic('ws')

@app.websocket('/feed')
async def feed(req,ws):
    while True:
        data =await ws.recv()
        print(data)
        if data is None:
            break

if __name__ == '__main__':
    import websockets
    import asyncio
    async def main():
        async with websockets.connect('ws://127.0.0.1::8889/feed') as ws:
            await ws.send('123')
            await ws.send(bytes(123))
    asyncio.get_event_loop().run_until_complete(main())`
run:gunicorn  main:app --bind 0.0.0.0:8889 --worker-class uvicorn.workers.UvicornWorker

**Comment by piekey1994** [comment] 2022-12-21 08:24
> I cannot reproduce this on `main`, or even on `22.3` using uvicorn.
> 
> ```python
> from sanic import Request, Sanic
> 
> app = Sanic("TestApp")
> 
> 
> @app.websocket("/feed")
> async def feed(request: Request, ws):
>     while True:
>         data = await ws.recv()
>         await ws.send(data)
> ```
> 
> I am closing this now as I see no bug. If you have a reproducible snippet, please send.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I started my sanic app with UvicornWorker. The original websocket will become WebsocketConnection. When I call
the ws.recv function will report an error if bytes data is received at this time.
`KeyError：‘text’`
[https://github.com/sanic-org/sanic/blob/main/sanic/server/websockets/connection.py](url)
`    async def recv(self, *args, **kwargs) -> Optional[str]:
        message = await self._receive()

        if message["type"] == "websocket.receive":
            return message["text"]
        elif message["type"] == "websocket.disconnect":
            pass

        return None`
There is no data of bytes type processed here.

### Code snippet

_No response_

### Expected Behavior

_No response_

### How do you run Sanic?

ASGI

### Operating System

ubuntu

### Sanic Version

22.3

### Additional context

_No response_

> I cannot reproduce this on `main`, or even on `22.3` using uvicorn.
> 
> ```python
> from sanic import Request, Sanic
> 
> app = Sanic("TestApp")
> 
> 
> @app.websocket("/feed")
> async def feed(request: Request, ws):
>     while True:
>         data = await ws.recv()
>         await ws.send(data)
> ```
> 
> I am closing this now as I see no bug. If you have a reproducible snippet, please send.

main.py
```
from sanic import Sanic

app = Sanic('ws')

@app.websocket('/feed')
async def feed(req,ws):
    while True:
        data =await ws.recv()
        print(data)
        if data is None:
            break

if __name__ == '__main__':
    import websockets
    import asyncio
    async def main():
        async with websockets.connect('ws://127.0.0.1::8889/feed') as ws:
            await ws.send('123')
            await ws.send(bytes(123))
    asyncio.get_event_loop().run_until_complete(main())
```
run: gunicorn  main:app --bind 0.0.0.0:8889 --worker-class uvicorn.workers.UvicornWorker

**Comment by ahopkins** [comment] 2022-12-21 10:05
Nope. Still works fine for me.

**Comment by piekey1994** [comment] 2022-12-22 01:05
> Nope. Still works fine for me.

That's weird. However, you can look at this code in sanic, and it does seem to have a problem. It seems to only handle text, right?
[connection.py](https://github.com/sanic-org/sanic/blob/main/sanic/server/websockets/connection.py)
```
    async def recv(self, *args, **kwargs) -> Optional[str]:
        message = await self._receive()

        if message["type"] == "websocket.receive":
            return message["text"]
        elif message["type"] == "websocket.disconnect":
            pass

        return None
```

**Comment by ahopkins** [comment] 2022-12-22 15:10
Yeah, will go back and look at the spec to see exactly what it's supposed to be.

**Closed** 2022-12-25 11:52 UTC
