### ISSUE TITLE
asyncio.CancelledError make the request hang

### ISSUE THREAD

**Issue by ziirish** [sanic-org/sanic#1971] opened 2020-11-18 20:36 UTC
**Describe the bug**
It appears we cannot cancel a task within the request handler.
I have some *long* running operations that I'd like to be able to cancel before Sanic timeout the request. But as soon as a asyncio.CancelledError is raised, the request hangs.

**Code snippet**
```python
import asyncio
from sanic import Sanic

app = Sanic(__name__)


@app.route("/cancel")
async def asyncio_cancel(request):
    raise asyncio.CancelledError


if __name__ == "__main__":
    app.run(debug=True)
```

**Expected behavior**
I expect the request to fail with a 500 immediately, instead I have to wait for SANIC_REQUEST_TIMEOUT and I don't have a clue what was going wrong (ie. no traceback or the like shows up in the logs):

```
[2020-11-18 21:24:26 +0100] [30951] [INFO] Server Stopped
[2020-11-18 21:24:26 +0100] [31269] [INFO] Starting worker [31269]
[2020-11-18 21:25:29 +0100] [31269] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/cancel'
NoneType: None
[2020-11-18 21:25:29 +0100] - (sanic.access)[INFO][127.0.0.1:50608]: GET http://localhost:8000/cancel  503 23
```

**Environment (please complete the following information):**
 - OS: Linux
 - Version: sanic-20.9.1 (but also reproductible on 20.6.3)

**Comment by ahopkins** [comment] 2020-11-19 09:17
This is somewhat unique exception because of how it gets used, and is not entirely surprising.

I think the best way for you would be to catch it yourself and not let it bubble up to Sanic. Here is an example where to recast it:

```python
class CustomCancelledError(SanicException):
    ...


def raise_cancelled_error():
    raise asyncio.CancelledError


@app.get("/")
async def get1(request):
    try:
        raise_cancelled_error()
    except asyncio.CancelledError as e:
        raise CustomCancelledError(e)
```

**Comment by ziirish** [comment] 2020-11-19 09:41
Thanks, that's indeed what I'm doing to workaround the problem but I'm not sure yet what causes Sanic to hang this way when the try/except are missing.

**Comment by ziirish** [comment] 2020-11-19 10:10
The reason I'm investigating on this issue is because I have some weird issues using Sanic with Gino.

I'm not able to reproduce the exact situation I'm facing at will, but here is what I have noticed so far:

```
[2020-11-19 10:58:12 +0100] [13503] [DEBUG] 

                 Sanic
         Build Fast. Run Fast.


[2020-11-19 10:58:12 +0100] [13503] [INFO] Goin' Fast @ http://127.0.0.1:8000
Executing <Task pending name='Task-2' coro=<Gino.init_app.<locals>.before_server_start() running at /home/bsans/.pyenv/versions/lab/lib/python3.8/site-packages/gino_sanic.py:116> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe24d1de5e0>()] created at /home/bsans/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py:471> cb=[run_until_complete.<locals>.<lambda>()] created at /home/bsans/.pyenv/versions/lab/lib/python3.8/site-packages/sanic/server.py:668> took 0.143 seconds
[2020-11-19 10:58:13 +0100] [13568] [INFO] Starting worker [13568]
sleeping [2020-11-19 10:58:22]
[2020-11-19 10:59:22 +0100] [13568] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/wait'
NoneType: None
[2020-11-19 10:59:22 +0100] - (sanic.access)[INFO][127.0.0.1:52348]: GET http://localhost:8000/wait  503 23
[2020-11-19 10:59:27 +0100] [13568] [INFO] Stopping worker [13568]
[2020-11-19 10:59:27 +0100] [13724] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/home/bsans/.pyenv/versions/lab/lib/python3.8/site-packages/sanic/server.py", line 915, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1727, in create_server
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
[2020-11-19 10:59:27 +0100] [13724] [INFO] Server Stopped
Pool.close() is taking over 60 seconds to complete. Check if you have any unreleased connections left. Use asyncio.wait_for() to set a timeout for Pool.close().
```

The last lines show an attempt to reload the server (I just `:w` in vim on the file to trigger sanic reloader)

The code I am running is:

```python
import time
import asyncio
from datetime import datetime
from sanic import Sanic
from sanic.response import empty
from gino.ext.sanic import Gino

app = Sanic(__name__)
app.config.DB_DSN = "postgres://test:test@localhost/test"
db = Gino()
db.init_app(app)


async def wait():
    now = datetime.now()
    print(f"sleeping [{now.strftime('%Y-%m-%d %H:%M:%S')}]")
    await db.first(db.text("SELECT pg_sleep(1)"))
    raise asyncio.CancelledError


@app.route("/wait")
async def waiting(request):
    start = time.time()
    task = asyncio.create_task(wait())
    await task
    end = time.time()
    print(f"waited for {end - start} seconds")
    return empty()


if __name__ == "__main__":
    app.run(debug=True)
```

Without Gino, I don't have this problem.

To be honest, I orgininaly suspected Gino to misbehave when a `asyncio.CancelledError` was being raised while a postgresql request was being processed, but so far the only problem I'm able to reproduce is when I'm using both Sanic and Gino together.

**Comment by ahopkins** [comment] 2022-01-08 23:38
@yckbilly1929 Do you have any code I can run to reproduce this? I am not sure if this is still a thing or not, or even what steps I should perform to attempt to reproduce this.

**Comment by yckbilly1929** [comment] 2022-01-09 03:38
> @yckbilly1929 Do you have any code I can run to reproduce this? I am not sure if this is still a thing or not, or even what steps I should perform to attempt to reproduce this.

i wondered that maybe I have initiated the app twice:

how i started the server
```
sanic app1.server.app
```

lines at the end of the file
```
if __name__ == "app1.server":
    logger.info("num of cores: %d; sanic version: %s", num_cores, sanic.__version__)
    server = app.run(host="0.0.0.0", port=8000, debug=False, access_log=False)
```

and thus
![Screenshot from 2022-01-09 11-37-02](https://user-images.githubusercontent.com/12884758/148668290-f9d49af3-d69a-4342-b26d-24917c281b7c.png)

**Comment by ahopkins** [comment] 2022-01-09 10:40
This is a completely unrelated issue and should be in its own issue, with a reference if you believe it is related.

**Comment by ahopkins** [comment] 2022-01-09 10:44
Closing this as I believe this is no longer an issue in v21.12.

**Closed by ahopkins** 2022-01-09 10:44 UTC
