### ISSUE TITLE
with --reload produce a zombie process problem

### ISSUE THREAD

**Issue by zybxjx** [sanic-org/sanic#2990] opened 2024-07-26 01:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With "start _ method = spell" and "- -reload" modify the code will produce a zombie process, modify the process.py-> _ terminate _ now() function, add self._current_process.join() after self._current_process.terminate() will not produce a zombie process, so ok?

### Code snippet

from sanic import Sanic
from sanic.response import text

app = Sanic("MyHelloWorldApp")

@app.get("/")
async def hello_world(request):
    # print('t')
    return text("Hello, world.")

### Expected Behavior

 produce a zombie process

### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

V24.6.0

### Additional context

    def _terminate_now(self):
        if not self._current_process.is_alive():
            return
        logger.debug(
            f"{Colors.BLUE}Begin restart termination: "
            f"{Colors.BOLD}{Colors.SANIC}"
            f"%s {Colors.BLUE}[%s]{Colors.END}",
            self.name,
            self._current_process.pid,
        )
        self._current_process.terminate()
        self._current_process.join() #new code

**Comment by ahopkins** [comment] 2024-12-15 14:43
I am not sure what is being asked here? Can you please clarify?

**Comment by zybxjx** [comment] 2024-12-27 09:42
Start With " Sanic.start_method = 'spawk' " and "- -reload", modify the code will produce a zombie process.

**Comment by ahopkins** [comment] 2024-12-31 07:43
Spawn is the default. I'm closing this for now because it is not clear at all how to reproduce. Feel free to elaborate and we can reopen.

**Closed** 2024-12-31 07:43 UTC
Labels: bug
