### ISSUE TITLE
'NoneType' object has no attribute 'share' when using create_server

### ISSUE THREAD

**Issue by johnwason** [sanic-org/sanic#2631] opened 2022-12-17 22:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am getting this error when using `app.create_server()` function on Windows:

```
'NoneType' object has no attribute 'share'
  File "c:\project\\software\venv\Lib\site-packages\sanic\server\runners.py", line 205, in _serve_http_1
    sock = sock.share(pid)
  File "c:\project\\software\venv\Lib\site-packages\sanic\server\runners.py", line 106, in serve
    return _serve_http_1(
  File "c:\project\\software\venv\Lib\site-packages\sanic\mixins\startup.py", line 451, in create_server
    return await serve(
  File "c:\project\\software\pyri-webui-server\src\pyri\webui_server\webui_server.py", line 100, in _run_server
    server = await self._app.create_server(self._host, self._port, return_asyncio_server=True) #sock=self._socket)
  File "C:\Python310\Lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\project\\software\pyri-webui-server\src\pyri\webui_server\webui_server.py", line 105, in run
    self._loop.run_until_complete(self._run_server())
  File "c:\project\\software\pyri-webui-server\src\pyri\webui_server\__main__.py", line 30, in main
    server.run()
  File "c:\project\\software\pyri-webui-server\src\pyri\webui_server\__main__.py", line 33, in <module>
    main()
  File "C:\Python310\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Lib\runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

If I create and pass a socket to create_server it seems to work.

### Code snippet

```python
async def _run_server(self):
        server = await self._app.create_server(self._host, self._port, return_asyncio_server=True)
        await server.startup()
        await server.serve_forever()
```

### Expected Behavior

Server should start normally.

### How do you run Sanic?

As a module

### Operating System

Windows 10

### Sanic Version

22.9.1

**Comment by ahopkins** [comment] 2022-12-18 11:43
Duplicate of #2558

**Closed by ahopkins** 2022-12-18 11:43 UTC
Labels: bug
