### ISSUE TITLE
app.run(workers=2) in bugs

### ISSUE THREAD

**Issue by jiayouzl** [sanic-org/sanic#2539] opened 2022-09-02 13:07 UTC
```
app.run(host=app.config['HOST'], port=app.config['PORT'], debug=app.config['DEBUG'], auto_reload=app.config['AUTO_RELOAD'], access_log=False,workers=1)
```
## There is no problem with the above code.

```
app.run(host=app.config['HOST'], port=app.config['PORT'], debug=app.config['DEBUG'], auto_reload=app.config['AUTO_RELOAD'], access_log=False,workers=2)
```

## The above code will report the following error after running.
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/7685337/188152567-448afff1-3cc6-4ad8-8a04-cfc93a31f7c6.png">

**Comment by ahopkins** [comment] 2022-09-02 13:17
How/where are you setting the env variables?

**Comment by jiayouzl** [comment] 2022-09-02 16:18
app.run(host="127.0.0.1", port=8081, debug=True, auto_reload=True, access_log=False,workers=2)

The above code will report the following error after running.

macos12.5.1 m1pro。

**Comment by jiayouzl** [comment] 2022-09-02 16:19
> How/where are you setting the env variables?

app.run(host="127.0.0.1", port=8081, debug=True, auto_reload=True, access_log=False,workers=2)

The above code will report the following error after running.

macos12.5.1 m1pro。

**Comment by jiayouzl** [comment] 2022-09-02 16:20
app.run(host="127.0.0.1", port=8081, debug=True, auto_reload=True, access_log=False,workers=1)

There is no problem with the above code.

macos12.5.1 m1pro。

**Comment by sjsadowski** [comment] 2022-09-02 17:08
I can confirm this, it appears that the subsequent workers are attempting to rebind to the port. Happens with the cli and specifying workers > 1 as well.

**Comment by sjsadowski** [comment] 2022-09-02 17:12
corollary issue: main process does not exit when breaking out with a keyboard interrupt from the above issue, it must be killed. It also continues to hold the port.

**Comment by jiayouzl** [comment] 2022-09-03 08:41
> 我可以确认这一点，看来后续工作人员正在尝试重新绑定到端口。如果保留 app.run 行，cli 和指定 workers > 1 也会发生。我认为我们需要记录优先顺序，但我认为 cli 参数应该最高？将把它移到不和谐的地方。



> I can confirm this, it appears that the subsequent workers are attempting to rebind to the port. Happens with the cli and specifying workers > 1 as well if the app.run line is left in. I think we need to document order of precedence, but I'd think cli arguments should have highest? Will move this to discord.

Hello, is this my problem or sanic's problem?

**Comment by sjsadowski** [comment] 2022-09-03 16:47
This appears to be a sanic issue. it can be worked around by running with your parameters specified from the CLI for now and commenting out your app.run() line

**Comment by ahopkins** [comment] 2022-09-03 17:48
Will look at this tomorrow. But even if there is an issue here it is moot as survey #2499 changes the behavior anyway.

**Comment by ahopkins** [comment] 2022-09-03 17:54
Okay... So I see now that you are running this on a Mac. Is this an M1? Perhaps it changes the behavior of socket tuple bindings. I'm not familiar with how m1 sockets may differ, will need to check that.

If I'm right then absolutely #2499 will change this as we bind the port only once and pass it to each spawned subprocess. Alternatively, in current version we rebind in each forked worker.

**Comment by jiayouzl** [comment] 2022-09-03 17:57
> Okay... So I see now that you are running this on a Mac. Is this an M1? Perhaps it changes the behavior of socket tuple bindings. I'm not familiar with how m1 sockets may differ, will need to check that.
> 
> If I'm right then absolutely #2499 will change this as we bind the port only once and pass it to each spawned subprocess. Alternatively, in current version we rebind in each forked worker.
Yes，my pc macbook pro m1pro。

**Comment by jiayouzl** [comment] 2022-09-03 17:58
> Okay... So I see now that you are running this on a Mac. Is this an M1? Perhaps it changes the behavior of socket tuple bindings. I'm not familiar with how m1 sockets may differ, will need to check that.
> 
> If I'm right then absolutely #2499 will change this as we bind the port only once and pass it to each spawned subprocess. Alternatively, in current version we rebind in each forked worker.



Yes，my pc macbook pro m1pro。

**Comment by sjsadowski** [comment] 2022-09-03 18:03
After further investigation, if I choose a completely unused port, I can't reproduce this on an m1 mac or on linux.

I accidentally chose a port in use for previous testing.

**Comment by ahopkins** [comment] 2022-09-04 06:26
@sjsadowski Wait... is the issue trying to run `sanic path.to.server:app` with `app.run(...)` in the file? Then yes, that is an anti-pattern and not the way the app should be run. The CLI is mutually exclusive with `app.run`.

![image](https://user-images.githubusercontent.com/166269/188300513-e0babde2-ab4b-4040-ac3f-6b2898872a7c.png)

**Comment by ahopkins** [comment] 2022-09-04 06:27
@jiayouzl What is the command that is being executed to invoke the server?

**Comment by jiayouzl** [comment] 2022-09-04 07:20
> @jiayouzl What is the command that is being executed to invoke the server?

I found out what the problem is.

## The following code will report an error
```
app.run(host=app.config['HOST'], port=app.config['PORT'], debug=app.config['DEBUG'], auto_reload=app.config['AUTO_RELOAD'], access_log=False,workers=2)
```

## The following code port can be run with int().
```
app.run(host=app.config['HOST'], port=int(app.config['PORT']), debug=app.config['DEBUG'], auto_reload=app.config['AUTO_RELOAD'], access_log=False,workers=2)
```

**Comment by ahopkins** [comment] 2022-09-04 10:34
Yes, the original problem was that you had a `str` for the port value. But it does not explain why, which is why I asked you how you were setting these config values to begin with.

Either way, I am closing this now. Feel free to keep the conversation going.

**Closed by ahopkins** 2022-09-04 10:34 UTC

**Comment by jiayouzl** [comment] 2022-09-04 11:19
> Yes, the original problem was that you had a `str` for the port value. But it does not explain why, which is why I asked you how you were setting these config values to begin with.
> 
> Either way, I am closing this now. Feel free to keep the conversation going.

Thank you very much!@ahopkins
