### ISSUE TITLE
Testing client breaks on Windows with Python3.8. 

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#1990] opened 2020-12-30 09:15 UTC
This is related to the streaming branch on #1876. For now we are skipping because it does work. The problem is with the testing client so that should not hold up the PR.

https://ci.appveyor.com/project/sjsadowski/sanic/builds/37044674/job/gdqi5wv157aci7wy

**Comment by ChihweiLHBird** [comment] 2021-07-07 20:06
Is this still an issue? I would like to look into it, if it still worth to be fixed. Any idea about how to reproduce it?

**Comment by ahopkins** [comment] 2021-07-08 06:15
I don't think the particular issue is. IIRC, I think that was something specific to appveyor, which we do not use anymore.

However, `.github/workflows/pr-windows.yml` was recently commented out because there was a problem with it. I think it had more to do with the build system though. If you want, open a PR and reenable that and see what the output is.

**Comment by ChihweiLHBird** [comment] 2021-08-09 20:22
@ahopkins Since the windows tests work well, can we close this issue?

**Closed** 2021-08-10 03:37 UTC
