### ISSUE TITLE
Unexpected behaviour with REQUEST_MAX_HEADER_SIZE

### ISSUE THREAD

**Issue by pluzun** [sanic-org/sanic#2917] opened 2024-02-14 20:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey,
It seems that the `REQUEST_MAX_HEADER_SIZE` don't rely only Headers size but also on the URL and Method leading to a `sanic.exceptions.PayloadTooLarge: Request header exceeds the size limit ` even if the headers size don't reach the max size: https://github.com/sanic-org/sanic/blob/v23.12.1/sanic/http/http1.py#L172-L197

See the following log with 2 requests with the same headers but with different URL:
```
sanic[2756545]: [2024-02-14 20:05:26 +0000] [2756545] [CRITICAL] 278 # Headers size 
sanic[2756545]: [2024-02-14 20:05:26 +0000] [2756545] [CRITICAL] [('host', '127.0.0.1:8000'), ('user-agent', 'python-httpx/0.11.1'), ('accept', '*/*'), ('accept-encoding', 'gzip, deflate'), ('connection', 'keep-alive'), ('content-type', 'application/json')]
sanic[2756545]: [2024-02-14 20:05:27 +0000] [2756545] [CRITICAL] 20571 # Headers size with big URL
sanic[2756545]: [2024-02-14 20:05:27 +0000] [2756545] [CRITICAL] [('host', '127.0.0.1:8000'), ('user-agent', 'python-httpx/0.11.1'), ('accept', '*/*'), ('accept-encoding', 'gzip, deflate'), ('connection', 'keep-alive'), ('content-type', 'application/json')]
```

### Expected Behavior

`REQUEST_MAX_HEADER_SIZE` should only take into account the HTTP Headers and not raise an Exception if the URL is too long.

### How do you run Sanic?

As a module

### Operating System

Linux

### Sanic Version

v23.12.1

**Comment by Tronic** [comment] 2024-02-15 22:23
This is intended functionality. HTTP/1 header consists of the request line and header lines, that together (also including the newlines that follow) must fit in this limit. Sanic by design cannot make a distinction between different parts of the header. Closing as not a bug.

**Closed** 2024-02-15 22:23 UTC
Labels: bug
