### ISSUE TITLE
21.9.0 Breaks Sentry Integration

### ISSUE THREAD

**Issue by Lagicrus** [sanic-org/sanic#2250] opened 2021-10-01 13:29 UTC
**Describe the bug**
With the new update and rewrite of some of the internals of Sentry, it has broken the [Sentry](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/sanic.py) Integration

**Code snippet**
https://starb.in/n2Q1Y5.py
<details><summary>Tracelog</summary>

```py
Error while handling error: sentry_error_handler_lookup() takes 2 positional arguments but 3 were given
Stack: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sanic/http.py", line 141, in http1
    await self.protocol.request_handler(self.request)
  File "sentry_handle_request", line 3, in sentry_handle_request
    import logging
NameError: name 'Hub' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handle_exception", line 28, in handle_exception
    Awaitable,
  File "/usr/local/lib/python3.8/site-packages/sanic/handlers.py", line 112, in response
    handler = self.lookup(exception, route_name)
TypeError: sentry_error_handler_lookup() takes 2 positional arguments but 3 were given
```

</details>

**Expected behaviour**
It not to break logging

**Environment (please complete the following information):**
 - Version:
   - Sanic: 21.9.0
   - Sentry: 1.4.3 & 1.3.1

**Comment by ahopkins** [comment] 2021-10-01 13:31
Per conversation on Discord, I will get a patch out tomorrow night. Thanks @Lagicrus.

**Comment by aericson** [comment] 2021-10-05 10:42
The PR mentioned this was fixed on 21.9.1 but I still get it on 21.9.1. Same stack trace as before.

**Comment by ahopkins** [comment] 2021-10-05 13:32
This is not the experience I am having. Can you show me how you are integrating? What version of the SDK are you using? This issues is outside of the scope of normal support for Sanic.

Here is a testable case that does pretty much the same thing that Sentry does.

```python
from sanic import Request, Sanic, text
from sanic.handlers import ErrorHandler

app = Sanic(__name__)


@app.get("/")
async def handler(request: Request):
    raise Exception("...")


@app.exception(Exception)
async def intercept(request: Request, exception: Exception):
    return text(str(exception), status=500)


set_aside = ErrorHandler.lookup


def monkeypatch_lookup(self, exception, *args, **kwargs):
    print(f"{exception=}")
    return set_aside(self, exception, *args, **kwargs)


ErrorHandler.lookup = monkeypatch_lookup
```

**Comment by ahopkins** [comment] 2021-10-05 13:35
Are you seeing:
```
You are using a deprecated error handler. The lookup method should accept two positional parameters: (exception, route_name: Optional[str]). Until you upgrade your ErrorHandler.lookup, Blueprint specific exceptions will not work properly. Beginning in v22.3, the legacy style lookup method will not work at all.
```

This is outside the typical support domain for Sanic since it is a plugin. What version of the SDK are you using?

**Comment by ahopkins** [comment] 2021-10-05 13:45
FWIW .... I am able to populate Sentry even on 21.9.0
![image](https://user-images.githubusercontent.com/166269/136035321-7cab268d-b5f6-4771-904c-db255b9bbfae.png)

**Comment by aericson** [comment] 2021-10-05 14:35
@ahopkins thanks! Yea, we are seeing the deprecation warning with sentry `sentry-sdk==1.4.3`.

I'll try to take a deeper look into it see if I can find the problem. I understand that it's outside the typical support domain, thanks for the help.

**Comment by ahopkins** [comment] 2021-10-05 14:50
@aericson FYI, there is also a conversation in the Discord server right now about this if you want to join in.

**Comment by ahopkins** [comment] 2021-10-07 08:33
That is true. Overriding `Sanic.handle_request` is a problem, but I think it might be dependent upon _WHEN_ you do it. Going to play around with this a little more myself.

**Comment by kamilogorek** [comment] 2021-11-04 12:20
I can confirm that our tests started to fail after `21.9.0` upgrade - https://github.com/getsentry/sentry-python/runs/3767107401?check_suite_focus=true

Local stacktrace for one of the failures:

```
INFO     sanic.root:testing.py:82 http://127.0.0.1:58248/message?foo=bar
ERROR    sanic.error:handlers.py:201 Exception occurred while handling uri: 'http://127.0.0.1:58248/message?foo=bar'
Traceback (most recent call last):
  File "/Users/kamilogorek/Projects/sentry/repositories/sentry-python/.tox/py3.9-sanic-21/lib/python3.9/site-packages/sanic/http.py", line 141, in http1
    await self.protocol.request_handler(self.request)
  File "sentry_handle_request", line 3, in sentry_handle_request
    import logging
NameError: name 'Hub' is not defined
INFO     sanic.access:http.py:483
INFO     sanic.root:runners.py:149 Starting worker [75565]
INFO     sanic.root:runners.py:152 Stopping worker [75565]
INFO     sanic.root:app.py:1061 Server Stopped
```

It looks like for some reason handler is not able to resolve local imports (note I'm not writing in python on daily basis, just debugging it in my spare time, so I might not know what I'm saying :3).

**Comment by ahopkins** [comment] 2021-11-04 23:09
@Lagicrus @aericson @kamilogorek 

Checkout the conversation in: https://github.com/getsentry/sentry-python/issues/1240
And, the updated PR: https://github.com/getsentry/sentry-python/pull/1212

**Comment by ahopkins** [comment] 2021-11-16 15:17
The fix for this in sentry is merged.

**Closed** 2021-11-16 15:17 UTC
