### ISSUE TITLE
put request returns error 405

### ISSUE THREAD

**Issue by rudyvan** [sanic-org/sanic#2089] opened 2021-03-25 16:04 UTC
with sanic version 20.12 the below code worked perfect when using a put statement following the first route definition.
(for completeness i added all the relevant routes)

```python3

@app_he.route("/api/<user_id>/lights/<id_num:string>/state", methods=["PUT"])
async def hue_api_put_light(request, user_id, id_num):
    """light change state request"""
    ...
    return resp

@app_he.route("/api/<user_id>/lights/<id_num:string>", methods=["GET"])
async def hue_api_individual_light(request, user_id, id_num):
    """individual device state, probably called to make sure command went through"""
    ...
    return response.json(my_a.hue_light(id_num))

```

Installing the latest version of sanic gives the follow error when using a put statement:

```
2021/03/25 12:15:41 !!Sanic except error http://192.168.15.31/api/h632JhAtwDezSwGk3VKEeFn4snXZUj1541885352/lights/bed%20light/state, Method PUT not allowed for URL /api/h632JhAtwDezSwGk3VKEeFn4snXZUj1541885352/lights/bed%20light/state
stack=/home/pi/lucy/lucy_app/base/logger.py@115,/home/pi/lucy/lucy_app/base/mail_print.py@266,/home/pi/lucy/lucy_app/base/pi_utils.py@534,/home/pi/lucy/lucy_app/base/pi_utils.py@427,/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/handlers.py@94,/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/app.py@624,/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/app.py@748,/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/http.py@125,/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/server.py@198,/home/pi/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py@44,/home/pi/lucy/lucy_app/base/tasker.py@278,/home/pi/lucy/main.py@10
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic_routing/route.py", line 84, in get_handler
    return self.handlers[raw_path][method][idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/router.py", line 33, in _get
    return self.resolve(
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic_routing/router.py", line 84, in resolve
    handler = route.get_handler(raw_path, method, handler_idx)
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic_routing/route.py", line 86, in get_handler
    raise self.router.method_handler_exception(
sanic_routing.exceptions.NoMethod: Method 'PUT' not found on <Route: name=Hue_emul.hue_api_user path=api/<user_id>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/app.py", line 679, in handle_request
    route, handler, kwargs = self.router.get(
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/router.py", line 61, in get
    return self._get(path, method, host)
  File "/home/pi/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sanic/router.py", line 41, in _get
    raise MethodNotSupported(
sanic.exceptions.MethodNotSupported: Method PUT not allowed for URL /api/h632JhAtwDezSwGk3VKEeFn4snXZUj1541885352/lights/bed%20light/state

```

when reverting to the older sanic version, with the below statement, everything works again as it should.
install "sanic>=20.12,<20.13" 

Is there an issue in the new routing script?

Kind Regards,
Rudy

**Comment by ahopkins** [comment] 2021-03-25 16:54
We just released a patch here: 

https://github.com/sanic-org/sanic-router/pull/13

On first glance, this might be the same problem. I am in my phone now so I cannot confirm. You can try upgrading the router

    pip install --upgrade sanic-routing

**Comment by johnwason** [comment] 2021-03-28 18:54
I am seeing the same issue with sanic-routing with the latest package.

**Comment by ahopkins** [comment] 2021-03-29 09:07
Using this:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic(__name__)


@app.route("/api/<user_id>/lights/<id_num:string>/state", methods=["GET"])
async def hue_api_put_light(request, user_id, id_num):
    return text("hue_api_put_light")


@app.route("/api/<user_id>/lights/<id_num:string>", methods=["GET"])
async def hue_api_individual_light(request, user_id, id_num):
    return text("hue_api_individual_light")


@app.after_server_start
def display(app, _):
    print(app.router.find_route_src)


app.run(port=9999, debug=True)
```

This problem seems resolved on current releases.

@johnwason Can you provide me with some examples of routes you are having issues with?

**Comment by ahopkins** [comment] 2021-03-29 09:59
@johnwason My apologies on this one. It looks like `0.4.2` was tagged missing the implemented change. Rereleased as `0.4.3`.

**Comment by sjsadowski** [comment] 2021-04-13 00:37
Were we able to confirm this was fixed in sanic-routing?

**Comment by ahopkins** [comment] 2021-04-17 23:18
Confirmed

**Closed** 2021-04-17 23:17 UTC
